### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by wlhlm** [zellneralex/klipper_config#1]
I have been compiling a my own Klipper configuration and have taken a few bits and pieces from this repository. Thank you for publishing your code. I want to upload my Klipper config to Github as well, unfortunately, as long as it includes pieces from your repository, I can't do this since your code doesn't include a license, which means it's "all rights reserved". I'd like to ask if you could consider choosing an open source license so that I'm allowed to publish my config with some of your code.

I recommend the GPLv3 license popular with many projects in the 3D printing space, but of course this decision is up to you. https://choosealicense.com/ gives you a good overview of open source licenses. Best practice is to include a copy of the license in a file called `LICENSE` in the repository.

**Comment by zellneralex** [comment]
Done
