### ISSUE TITLE
Board mapping

### ISSUE THREAD

**Issue by reiczel01** [zellneralex/klipper_config#14]
Is there any chance you could do a mapping guide for other boards like Octopus?

**Comment by zellneralex** [comment]
The chances are pretty low.

First my cfg should be seen more as examples what you can do with macros then a ready to copy solution.
Second, mapping the pins from your mcu might involves some compromises depending on your hardware. That are individual decisions.
Third any cfg provided for an V2 should work. The names of many parts like steppers, bed, extruder must follow the klipper definition and therefor needs to be the same anyhow.
Last but not least if you struggle already getting the right pin numbers in, then I fear you will not be able to adopt the user definitions and more important fix it after an klipper update.
You should always ask yourself, would I be able to get back to an working printer myself after an klipper update that break something.

**Here a few general advices:**
1) find the board pinout:
    - vendor schematic/drawing/wiki
    - board specific cfg file in the klipper/config folder
    - worst case Marlin C Header files
2) most of the stuff like heater_bed, stepper, extruder, display, or fan use klipper defined names start with them.
3) after that write down what you have left to connect and what you need for that (logic input e.g. filament runout sensor, logic output e.g. PWM signal of an 4 wire fan, mosfet driven output e.g. extra 2 wire fan ...)
4) write down what you have left on your mcu. Consider what you might need in addition e.g. linux mcu on the PI, smth like an klipper expander, external mosfet module ...
5) Map the remaining HW to your pins.

The 5 points above are a general advice for any board/printer combination and have nothing to do with any specific cfg.

In general I see that newer boards like Spider or Octopus have enough output pins (logic and mosfet driven) but might get in trouble at the possible input pins if you run many 4 wire fans, filament sensors and e.g gcode buttons. There a pico PI module or an linux mcu on the PI could be a good addition to solve that.

I know I putted extra work in that cfg to make it easier to adopt, that makes me already trouble testing my stuff (and generates escapes bugs for others with none placed HW), but that was done to reduce the amount of questions I get how to adopt it.
Adding now guides/examples of board pinouts/examples that I do not own and have in my machine would add the next level of complexity and risks of bugs.
