### ISSUE TITLE
Typo in printer.cfg

### ISSUE THREAD

**Issue by kwalters3** [zellneralex/klipper_config#22]
Noticed a typo in your printer.cfg in section [gcode_macro _EXECUTE_AT_INIT].

{% if user.hw.relay,ena %} _HEATER_ON {% endif %}

This causes the if to always be true.  Modifying your configs for my voron 2.4 kept giving message about _HEATER_ON macro being non existent.

**Comment by zellneralex** [comment]
Thank you see https://github.com/zellneralex/klipper_config/commit/21884018f68d197fdab42cdbbe313b09e85e25b4
