### ISSUE TITLE
Controller fan stays on after print, printer will not go into sleep

### ISSUE THREAD

**Issue by Piranha1511** [zellneralex/klipper_config#24]
Hi Alex,

sorry for another question/issue. I really like your config and it is running now really well. Only one thing is left and you can give me maybe an advise:

My printer is not going into sleep after a print, which means my controller fan stays permanently on until I manually shutdown my printer. 

Do you have an idea where I should have a look at?

**Comment by zellneralex** [comment]
Why should your printer go to sleep? Anyway look in your idle_timeout definition. Take care my config delays the stop of nevermore and the exhaust fan by 30 min to cool down the chamber and remove fume

**Comment by Piranha1511** [comment]
If I print during night and the printer finished the print job, I would expect that after cool down the controller fan will also switch off. 

Yes, the nevermore and chamber is same on my printer. But still the controller fan stays on the whole night.

**Comment by Piranha1511** [comment]
What I just experienced:

It works as long as I just heat up the printer and cool down again without a print. But it seems that the idle routine will not be executed if there was a print before. 

Example in the screenshot. Idle wasn't executed after 30 Min. Than I restarted the firmware. Heated up (idle time was 120sec. for testing) and idle was executed. So it only stuck after a print
<img width="606" alt="Bildschirm­foto 2023-01-08 um 13 05 00" src="https://user-images.githubusercontent.com/6705464/211195100-a4564c42-11a3-47f2-8082-28b84566b7dd.png">

**Comment by zellneralex** [comment]
I do not know your config and GitHub is not the place do debug your stuff and ask question about your config.

idle_timeout also works after printering. Maybe search for a delayed_gcode the restarts the idle timeout every time. BTW if you use my setup the idle timeout would be 2h

**Comment by Piranha1511** [comment]
Yes, no worries! Will figure it out.

**Comment by zellneralex** [comment]
Try to reach me in any of the discord servers
