### ISSUE TITLE
Homing Motor Current

### ISSUE THREAD

**Issue by retsamedoc** [zellneralex/klipper_config#3]
Why change motor current during homing/QGL moves? Does this help improve accuracy or is it to protect against toolhead crashes from causing damage?

**Comment by zellneralex** [comment]
The Voron V2 uses 4 geared motors that produce a lot of force. The reduction is only to increase the chance to survive a head crash without bending the gantry

**Comment by retsamedoc** [comment]
Is there a good method to determine what a good homing current is?

**Comment by zellneralex** [comment]
try and error
