### ISSUE TITLE
Info Request: Hardware used

### ISSUE THREAD

**Issue by TravisWilder** [zellneralex/klipper_config#5]
Hello
can you please "document" which hardware you use?
Like which Stepper Motors?
Heater? may be LED etc...

Thanks

**Comment by zellneralex** [comment]
Hi,

sorry that is my config and my printer. You can use my config to get a idea how to solve macro problems or setup something. But that is not meant to be a direct copy for your's nor it should replace any voron BOM.

I will add the information I like to be public but I will not add any detail of my machine.

**Comment by zellneralex** [comment]
If you like to ask me smth you will find me at the voron, klipper or mainsail discord
