### ISSUE TITLE
Typo in BED_MESH_STORE macro

### ISSUE THREAD

**Issue by zztopper** [zellneralex/klipper_config#6]
https://github.com/zellneralex/klipper_config/blob/6392741ea4d26e69c73587c990178db9b7d5ed8d/bed_mesh.cfg#L132

This should be
`SET_GCODE_VARIABLE MACRO=BED_MESH_STORE VARIABLE=save_at_end VALUE='"true"'`
to work properly

**Comment by zellneralex** [comment]
Fixed thank you
