### ISSUE TITLE
Invalid M204 command "M204 P2000"

### ISSUE THREAD

**Issue by anteyru** [zellneralex/klipper_config#7]
During printing, lines are constantly popping up by type
// Invalid M204 command "M204 P2000"

**Comment by zellneralex** [comment]
My M204 follows the klipper rule 

Set acceleration: M204 S[value] OR M204 P[value] T[value]
Note: If S is not specified and both P and T are specified, then the acceleration is set to the minimum of P and T. If only one of P or T is specified, the command has no effect.

So either change you gcode flavor or modify my macro to also allow to accept M204 P[value]
